### ISSUE TITLE
Question: Does this library provide enough to base a JMeter test on?

### ISSUE THREAD

**Issue by jeroenhabets** [UOC/java-lti-1.3#20]
Hi,

Apologies, to barge in like this but I am looking into Java (or Groovy) LTI 1.3 libraries so we can develop a JMeter load test for our LTI tool.

Is that something you may have had to develop here to integration test this library for LTI tools? Or is there a better place/project to look for an answer.

Any pointers will be appreciated.

Thanks in advance,
Jeroen

**Comment by xaviaracil** [comment]
Hi @jeroenhabets,

We haven't develop any regarded integration tests, only unit tests. Any help with that will be highly appreciated, thought this may be not the best place to develop them. Maybe https://github.com/UOC/spring-boot-lti-advantage is a better place to add them.

What do you think?

Regards,
Xavi

**Comment by jeroenhabets** [comment]
Hi @xaviaracil,

You're probably right as with LTI 1.3 the platform (client) needs to host an OIDC service (and cannot be a pure client). Now I need to read up more on JMeter if that enables you to host a service... If not, a proxy service is needed and in my company that we have considered before but would probably be developed in .Net (or Python). 

If I personally end up digging into it I will consider your [spring-boot-lti-advantage](https://github.com/UOC/spring-boot-lti-advantage) option, though.

Thanks for your help! and who knows... 

Kind regards, Jeroen
