### ISSUE TITLE
Publish on Maven Central

### ISSUE THREAD

**Issue by tomkuipers** [UOC/java-lti-1.3#4]
Thank you for your work, this is very useful! Please publish on Maven Central as this makes it much more easier to use this as dependency in projects.

**Comment by xaviaracil** [comment]
Thanks Tom! 
I've published on Github Packages. To use it, here's the link for configuring maven: https://help.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/configuring-apache-maven-for-use-with-github-packages
